kind: pipeline
name: workshop-demo-app

steps:
  - name: pytest
    image: python
    commands:
      - pip install -r requirements.txt
      - pytest --cov-report xml --cov-report term --cov ./lib

steps:
  - name: publish
    image: plugins/ecr
    settings:
      access_key: a50d28f4dd477bc184fbd10b376de753
      secret_key: bc5785d3ece6a9cdefa42eb99b58986f9095ff1c
      repo: 689970811091.dkr.ecr.eu-west-1.amazonaws.com/drone
      registry: 689970811091.dkr.ecr.us-west-1.amazonaws.com
