kind: pipeline
type: docker
name: workshop-demo-app

steps:
- name: pytest2
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest --cov-report xml --cov-report term --cov ./lib/

trigger:
  branch:
  - develop
  event:
  - push